ProjetoEmprestimoLivros/Models/LivrosModel.cs
using System.ComponentModel.DataAnnotations;

namespace ProjetoEmprestimoLivros.Models
{
    public class LivrosModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Titulo { get; set; } = string.Empty;
        [Required]
        public string Descricao { get; set; } = string.Empty;
        [Required]
        public string Capa { get; set; } = string.Empty;
        [Required]
        public string ISPB { get; set; } = string.Empty;
        [Required]
        public string Autor { get; set; } = string.Empty;
        [Required]
        public string Genero { get; set; } = string.Empty;
        [Required]
        public int AnoPublicacao { get; set; }
        [Required]
        public int QuantidadeEmEstoque { get; set; }
        public DateTime DataDeCadastro { get; set; } = DateTime.Now;
        public DateTime DataDeAlteracao { get; set; } = DateTime.Now;




    }
}

ProjetoEmprestimoLivros/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ProjetoEmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {


        public IActionResult Index()
        {
            return View();
        }

    }
}

ProjetoEmprestimoLivros/Controllers/LivroController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoEmprestimoLivros.Models;
using ProjetoEmprestimoLivros.Services.LivroService;

namespace ProjetoEmprestimoLivros.Controllers
{
    public class LivroController : Controller
    {
        private readonly ILivroInterface _livroInterface;
        public LivroController(ILivroInterface livroInterface)
        {
            _livroInterface = livroInterface;
        }
        public async Task<ActionResult<List<LivrosModel>>> Index()
        {
            var livros = await _livroInterface.BuscarLivros();

            return View(livros);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

    }
}

ProjetoEmprestimoLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetoEmprestimoLivros/Views/Livro/Cadastrar.cshtml
@using ProjetoEmprestimoLivros.DTO
@model LivroCriacaoDto

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-dark" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger text-dark" role="alert">
        @TempData["MensagemErro"]
    </div>
}


<div class="container mt-5">
    <form method="post" asp-action="Cadastrar" asp-controller="Livro" enctype="multipart/form-data">
        <h2>Cadastro de Livros</h2>

        <div class="text-center">
            <label for="ImageFile">
                <img id="img" style="width:150px; height:200px" />
            </label>
        </div>

        <div class="mb-1">

            <label class="form-label mt-3">Capa:</label>
            <input type="file" id="ImageFile" name="foto" class="form-control shadow-none" />


        </div>
        <div class="mb-1">
            <label class="form-label">Titulo:</label>
            <input type="text" asp-for="Titulo" class="form-control shadow-none">
            <span class="text-danger" asp-validation-for="Titulo"></span>
        </div>
        <div class="mb-1">
            <label class="form-label">Autor:</label>
            <input type="text" asp-for="Autor" class="form-control shadow-none">
            <span class="text-danger" asp-validation-for="Autor"></span>
        </div>
        <div class="mb-1">
            <label class="form-label">Descricao:</label>
            <textarea asp-for="Descricao" class="form-control shadow-none"></textarea>
            <span class="text-danger" asp-validation-for="Descricao"></span>
        </div>
        <div class="col-12 d-flex gap-1 w-100">
            <div class="mb-1 col-6">
                <label class="form-label">Ano Publicação:</label>
                <input type="text" asp-for="AnoPublicacao" class="form-control shadow-none">
                <span class="text-danger" asp-validation-for="AnoPublicacao"></span>
            </div>
            <div class="mb-1 col-6">
                <label class="form-label">Genero:</label>
                <input type="text" asp-for="Genero" class="form-control shadow-none">
                <span class="text-danger" asp-validation-for="Genero"></span>
            </div>
        </div>
        <div class="col-12 d-flex gap-1 w-100">
            <div class="mb-1 col-6">
                <label class="form-label">Quantidade em estoque:</label>
                <input type="number" asp-for="QuantidadeEmEstoque" class="form-control shadow-none" min="1">
                <span class="text-danger" asp-validation-for="QuantidadeEmEstoque"></span>
            </div>
            <div class="mb-1 col-6">
                <label class="form-label">ISBN:</label>
                <input type="text" id="isbn" asp-for="ISPB" class="form-control shadow-none">
                <span class="text-danger" asp-validation-for="ISPB"></span>
            </div>
        </div>




        <div class="btn-box d-flex mt-3">
            <button type="submit" type="button" class="btn btn-success w-50 mx-1"><i class="bi bi-plus-circle"></i> Cadastrar!</button>
            <a type="submit" class="btn btn-info w-50" asp-controller="Livro" asp-action="Index"><i class="bi bi-arrow-left-circle"></i> Voltar</a>
        </div>

    </form>
</div>





<script>


    const inputFile = document.querySelector("#ImageFile");

    inputFile.addEventListener("change", function (e) {
        const inputTarget = e.target;
        const file = inputTarget.files[0];

        if (file) {
            const reader = new FileReader();

            reader.addEventListener("load", function (e) {
                const readerTarget = e.target;
                const img = document.querySelector("#img");
                img.src = readerTarget.result;

                const figcaption = document.querySelector("#figcaption");
                figcaption.innerHTML = file.name;
            });

            reader.readAsDataURL(file);
        }
    }


    )
</script>

ProjetoEmprestimoLivros/Views/Livro/Index.cshtml
@using ProjetoEmprestimoLivros.Models
@model IEnumerable<LivrosModel>

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-dark" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger text-dark" role="alert">
        @TempData["MensagemErro"]
    </div>
}


<div class="container mt-5">

    <div class="btn-box d-flex justify-content-between align-items-center mb-3">
        <h2>Cadastro de livros!</h2>
        <a class="btn btn-success" asp-action="Cadastrar" asp-controller="Livro"><i class="bi bi-plus-circle"></i>  Cadastrar novo livro</a>
    </div>

    <table class="table table-hover" id="registros">
        <thead>
            <tr>
                <th></th>
                <th>Titulo</th>
                <th>Autor</th>
                <th>Genero</th>
                <th>Quantidade em Estoque</th>
                <th>Data de cadastro</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                @if (Model.Count() > 0)
                {
                    @foreach (var livros in Model)
                    {

                        <tr>
                            @if (livros.Capa != null)
                            {
                                <td>
                                    <img src="imagem/@livros.Capa" style="width:50px; height: 50px" />
                                </td>
                            }
                            else
                            {
                                <td>
                                </td>
                            }



                            <td><i class="bi bi-people"></i>@livros.Titulo</td>
                            <td>@livros.Autor</td>
                            <td>@livros.Genero</td>
                            <td><i class="bi bi-envelope-at"></i>@livros.QuantidadeEmEstoque</td>
                            <td><i class="bi bi-calendar"></i>@livros.DataDeCadastro</td>
                            <td>
                                <a class="btn btn-warning" asp-action="Detalhes" asp-controller="Livro" asp-route-id="@livros.Id"><i class="bi bi-file-earmark-zip"></i>Detalhes</a>
                                <a class="btn btn-info" asp-action="Editar" asp-controller="Livro" asp-route-id="@livros.Id"><i class="bi bi-pencil"></i>Editar</a>
                            </td>
                        </tr>
                    }

                }
                else
                {
                    <tr><td colspan="6" class="text-center">Sem Livros Registrados!</td></tr>
                }

            }






        </tbody>
    </table>


</div>

ProjetoEmprestimoLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoEmprestimoLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/lux.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoEmprestimoLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoEmprestimoLivros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>